### ISSUE TITLE
Regression: 1.54 cannot update Dokuwiki any more

### ISSUE THREAD

**Issue by hartwork** [gentoo/webapp-config#2]
It seems I cannot udpate Dokuwiki any more. webapp-config is complaining that the version I am passing is invalid. I don't see why:

```
# webapp-config --user apache --group apache --host www.example.org -d '.' --upgrade dokuwiki 20140929d
* Fatal error: Invalid package version: 20140929d
* Fatal error(s) - aborting

# webapp-config --user apache --group apache --host www.example.org -d '.' --upgrade dokuwiki 20140929d-r1
* Fatal error: Invalid package version: 20140929d-r1
* Fatal error(s) - aborting

# ls -d1 /var/db/pkg/www-apps/dokuwiki-*
/var/db/pkg/www-apps/dokuwiki-20140929b
/var/db/pkg/www-apps/dokuwiki-20140929c
/var/db/pkg/www-apps/dokuwiki-20140929d
/var/db/pkg/www-apps/dokuwiki-20140929d-r1
```

If this is not a bug, please help me understand what I am doing wrong. Many thanks!

**Comment by hartwork** [comment]
I downgraded to 1.53-r2 by now. With 1.53-r2, the upgrade works without complaints:

```
# webapp-config --user apache --group apache --host www.example.org --upgrade dokuwiki 20140929d-r1
* Upgrading /dokuwiki-20140929c to /dokuwiki-20140929d-r1
[..]
* Install completed - success
```

**Comment by twitch153** [comment]
That'd be an issue on my part. I'll fix it and release a new revision of webapp-config-1.54 with the patch :+1:

**Comment by hartwork** [comment]
Cool, thank you!

**Comment by twitch153** [comment]
Not a problem! Thank you for letting me know.

**Comment by twitch153** [comment]
The ebuild is on the tree and the fix is in the repo, I'll be closing this issue now.

**Comment by hartwork** [comment]
Excellent, thank you!

For the record, it's commit 9e251c7574d074e424ea19024f743c754f321979.
